FROM registry.fedoraproject.org/fedora:44

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    --mount=type=cache,target=/var/lib/dnf \
    echo "keepcache=True" >> /etc/dnf/dnf.conf && \
    dnf upgrade -y

COPY entrypoint/dotfiles/ /root/

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y \
                   alsa-lib-devel \
                   ansible \
                   ant \
                   antlr4 \
                   antlr4-cpp-runtime \
                   antlr4-cpp-runtime-devel \
                   aria2 \
                   asciidoctor \
                   asciinema \
                   attr \
                   audit-libs-devel \
                   autoconf \
                   automake \
                   bash-completion \
                   bat \
                   bc \
                   bear \
                   bind-utils \
                   binutils-devel \
                   binutils-gold \
                   bison \
                   blas-devel \
                   bmon \
                   boost-devel \
                   bpftrace \
                   btop \
                   buildah \
                   bzip2 \
                   bzip2-devel \
                   cabal-install \
                   ca-certificates \
                   cairo-devel \
                   cargo \
                   ccache \
                   clang \
                   clang-analyzer \
                   clang-devel \
                   clang-tools-extra \
                   clisp \
                   cloc \
                   clojure \
                   cmake \
                   colordiff \
                   cppcheck \
                   cronie \
                   cscope \
                   ctags \
                   curl \
                   dbus-devel \
                   ddrescue \
                   diffutils \
                   direnv \
                   distcc \
                   doxygen \
                   duf \
                   eigen3-devel \
                   elixir \
                   emacs \
                   emacs-gtk+x11 \
                   emacs-pgtk \
                   entr \
                   erlang \
                   ethtool \
                   expat-devel \
                   expect \
                   eza \
                   fakeroot \
                   fd-find \
                   fdupes \
                   ffmpeg-free \
                   fftw-devel \
                   file \
                   firefox \
                   firewalld \
                   fish \
                   flex \
                   fontconfig-devel \
                   freetype-devel \
                   fuse-overlayfs \
                   fzf \
                   gawk \
                   gcc \
                   gcc-c++ \
                   gdb \
                   gettext \
                   gettext-devel \
                   gh \
                   ghc \
                   giflib-devel \
                   git \
                   git-lfs \
                   glew-devel \
                   glib2-devel \
                   glibc-static \
                   gmp-devel \
                   gnupg2 \
                   gnuplot \
                   golang \
                   google-perftools-devel \
                   gopls \
                   gource \
                   gperf \
                   graphviz \
                   groff \
                   gsl-devel \
                   gtest-devel \
                   gtk3-devel \
                   gtk4-demo \
                   gtk4-devel \
                   heaptrack \
                   htop \
                   httpie \
                   hyperfine \
                   ImageMagick \
                   inotify-tools \
                   iotop \
                   iperf3 \
                   iproute \
                   ipset \
                   iptables \
                   iputils \
                   jansson-devel \
                   java-25-openjdk \
                   java-25-openjdk-devel \
                   jq \
                   julia \
                   kcachegrind \
                   lapack-devel \
                   less \
                   leveldb-devel \
                   libacl-devel \
                   libarchive-devel \
                   libasan \
                   libcap-devel \
                   libcurl-devel \
                   libcxx-devel \
                   libdrm-devel \
                   libev-devel \
                   libevent-devel \
                   libffi-devel \
                   libgcrypt-devel \
                   libgit2-devel \
                   libglvnd-gles \
                   libheif-devel \
                   libjpeg-turbo-devel \
                   libnotify \
                   libogg-devel \
                   libpcap-devel \
                   libpng-devel \
                   librsvg2-devel \
                   libseccomp-devel \
                   libselinux-devel \
                   libsodium-devel \
                   libssh2-devel \
                   libssh-devel \
                   libstdc++-static \
                   libtiff-devel \
                   libtool \
                   libubsan \
                   libuv-devel \
                   libvorbis-devel \
                   libwebp-devel \
                   libXcomposite \
                   libxcrypt-devel \
                   libXcursor \
                   libXdamage \
                   libXfixes \
                   libXft \
                   libXi \
                   libXinerama \
                   libxml2-devel \
                   libXmu \
                   libXrandr \
                   libXrender \
                   libXres \
                   libXScrnSaver \
                   libxslt-devel \
                   libXtst \
                   libXv \
                   libXxf86vm \
                   libyaml-devel \
                   libzip-devel \
                   libzip-tools \
                   lld \
                   lldb \
                   lmdb-devel \
                   lsb_release \
                   lsof \
                   ltrace \
                   lua \
                   lua-devel \
                   luarocks \
                   lz4 \
                   lz4-devel \
                   m4 \
                   make \
                   man-db \
                   man-pages \
                   mariadb \
                   mariadb-devel \
                   maven \
                   memcached \
                   mercurial \
                   mesa-demos \
                   mesa-dri-drivers \
                   mesa-libEGL-devel \
                   mesa-libGL-devel \
                   meson \
                   mingw64-gcc \
                   mold \
                   moreutils \
                   mosh \
                   mpfr-devel \
                   mpv \
                   mtr \
                   nano \
                   nasm \
                   ncdu \
                   ncurses-devel \
                   neovim \
                   nethogs \
                   nettle-devel \
                   net-tools \
                   nginx \
                   ninja-build \
                   nlohmann-json-devel \
                   nmap \
                   nodejs \
                   npm \
                   nss-tools \
                   ocaml \
                   octave \
                   oniguruma-devel \
                   openblas-devel \
                   openldap-devel \
                   openssh-clients \
                   openssl-devel \
                   p7zip \
                   pandoc \
                   pango-devel \
                   parallel \
                   patch \
                   patchutils \
                   pcre2-devel \
                   perf \
                   perl \
                   perl-Image-ExifTool \
                   php \
                   php-cli \
                   php-devel \
                   pigz \
                   pinentry \
                   pipewire-devel \
                   pkgconf-pkg-config \
                   plocate \
                   podman \
                   polkit-devel \
                   poppler-utils \
                   postgresql \
                   postgresql-devel \
                   pre-commit \
                   procps-ng \
                   procs \
                   progress \
                   protobuf-compiler \
                   pv \
                   python3 \
                   python3-black \
                   python3-cython \
                   python3-devel \
                   python3-ipython \
                   python3-matplotlib \
                   python3-mypy \
                   python3-notebook \
                   python3-numpy \
                   python3-pandas \
                   python3-pip \
                   python3-pylint \
                   python3-pytest \
                   python3-pytest-xdist \
                   python3-requests \
                   python3-scipy \
                   python3-setuptools \
                   python3-sphinx \
                   python3-sympy \
                   python3-tomli \
                   python3-twisted \
                   python3-virtualenv \
                   python3-wheel \
                   python3-yaml \
                   qemu \
                   qt5-qtbase-devel \
                   qt6-qtbase-devel \
                   qt6-qtbase-examples \
                   R \
                   radare2 \
                   ragel \
                   rclone \
                   R-core-devel \
                   re2c \
                   readline-devel \
                   redis \
                   ripgrep \
                   rpm-build \
                   rpmdevtools \
                   rsync \
                   ruby \
                   ruby-devel \
                   ruff \
                   rustfmt \
                   samba-client \
                   sbcl \
                   scons \
                   SDL2_image-devel \
                   SDL3-devel \
                   SDL3_sound \
                   SDL3_sound-devel \
                   sed \
                   ShellCheck \
                   shfmt \
                   skopeo \
                   socat \
                   sox \
                   spdlog-devel \
                   speedtest-cli \
                   sqlite \
                   sqlite-devel \
                   strace \
                   stress-ng \
                   swift-lang \
                   swig \
                   sysbench \
                   sysstat \
                   systemd-devel \
                   tcpdump \
                   tesseract \
                   texinfo \
                   the_silver_searcher \
                   tig \
                   tinyxml2-devel \
                   tldr \
                   tmate \
                   tmux \
                   tokei \
                   traceroute \
                   tree \
                   ty \
                   units \
                   unzip \
                   uv \
                   valgrind \
                   vim-enhanced \
                   vulkan-tools \
                   wabt \
                   wayland-devel \
                   wget \
                   which \
                   whois \
                   wireguard-tools \
                   wl-clipboard \
                   xclip \
                   xdotool \
                   xmlstarlet \
                   xorg-x11-server-Xvfb \
                   xz \
                   xz-devel \
                   yasm \
                   yq \
                   zig \
                   zip \
                   zlib-devel \
                   zsh \
                   zstd \
                   && \
    echo "source ~/.extrabashrc" >> ~/.bashrc


RUN echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc

# Install Claude Code (native binary, no Node.js required)
RUN curl -fsSL https://claude.ai/install.sh | bash

RUN source ~/.bashrc && claude update

ENTRYPOINT ["/entrypoint.sh"]
